### PR TITLE
Fix for Bug #108415 - Occasional NPE when server dies

### PR DESCRIPTION
**Pull request by amilbourne**
This just adds a very simple null-check guard as suggested in the bug report here:
https://bugs.mysql.com/bug.php?id=108415

I have not added a test as this is a very small change and probably not worth the overhead of a test.  Also, this is my first contribution and I have no idea how to test this.

I confirm the code being submitted is offered under the terms of the OCA, and that I am authorized to contribute it.

### CODE REVIEW

**Comment by amilbourne** [comment]
My OCA has been approved and I have a working bug system account.  Hopefully this PR can now be considered.

**Comment by mysql-admin** [comment]
Hi @amilbourne ,
We need the bug user in place so we can associate the OCA with it 

Thanks for contributing to MySQL
==Omer

**Comment by amilbourne** [comment]
Sorry, I'm unclear whether you are asking me to do something.  I have commented on the bug so you should be able to see my bug account user (if that is the issue).  The OCA should be linked to that account.

**Comment by mysql-admin** [comment]
Hi @amilbourne ,
I understood from the above as if you need to set a bug system user. I now see that you already have one in place. 
No action is needed. Shortly, the bot will ask you to confirm the contribution is under OCA and after that will process the PR

Sorry for the confusion and thanks for contributing to MySQL 
==Omer

**Comment by swarren12** [comment]
What is the status of this. The PR was closed on Jan 10, but it hasn't been merged and the 8.1 release still contains the bug.

**Comment by swarren12** [comment]
From https://github.com/mikevink/mysql_connector_j_8_npe/blob/github/readme.md:

> It appears that the AbstractQuery implementation has its inner query closed during the NativeSession cleanup triggered by the server disconnect on line 684 (a CJCommunicationsException in NativeSennion::execSQL), which makes sense. The StatementImpl, however, isn't made aware of the communication exception, and it attempts to clean up the timers it had previously started, which leads to the NPE.

This makes me wonder if the null-check is actually the correct solution after all? Could this lead to a leak where the timer isn't cleaned up from the session?

**Comment by amilbourne** [comment]
@swarren12 I didn't investigate the cause myself and implemented the (sensible sounding) solution in the initial bug report - and on the page you quote from.  

The very bottom of the page you are quoting from says:

> The Timer which schedules the CancelQueryTaskImpl in AbstractQuery::startQueryTImer line 213 does not receive the purge() call it should. As the task gets cancelled anyway, this is likely not a problem, but we are not familiar enough with the rest of the code to be certain.

So a timer leak is certainly possible, but the original investigation thought that it probably wasn't a problem.

Either way, the null check won't make any possible timer leak worse, although it would make it less obvious.

I'm not clear why it hasn't been released.

**Pull request closed without merging**
