### PR TITLE
Replace synchronized with ReentrantLock

### PR DESCRIPTION
**Pull request by bdeneuter**
Replace synchronized blocks with a ReentrantLock. This avoids that the carrier thread (OS thread) is pinned when running on virtual threads which were introduced as a preview feature in JDK 19.

The JEP that is being prepared for JDK 21 still contains the limitation:
https://openjdk.org/jeps/8303683

`There are two scenarios in which a virtual thread cannot be unmounted during blocking operations because it is pinned to its carrier:

 When it executes code inside a synchronized block or method, or
 When it executes a native method or a foreign function.`

This PR makes the following PRs obsolete as it replaces them:
https://github.com/mysql/mysql-connector-j/pull/91
https://github.com/mysql/mysql-connector-j/pull/93

### CODE REVIEW

**Comment by bdeneuter** [comment]
I confirm the code being submitted is offered under the terms of the OCA, and that I am authorized to contribute it.

**Comment by masoudparvari** [comment]
Is there any plan to get this merged ?

**Comment by fjssilva** [comment]
Hi @masoudparvari, we do have plans to analyze it thoroughly and may consider merging it. That work hasn't been completed yet. It's a significant change and we need to be very careful to avoid causing damage to others. I hope you understand. Thanks,

**Comment by zzhujing** [comment]
> Hi @masoudparvari, we do have plans to analyze it thoroughly and may consider merging it. That work hasn't been completed yet. It's a significant change and we need to be very careful to avoid causing damage to others. I hope you understand. Thanks,

how long ? i want to use virtual threads with mysql ..

**Comment by He-Pin** [comment]
Why this was closed :(

image

**Comment by fjssilva** [comment]
It's how Oracle MySQL's contribution process works. Follow up in the bug report mentioned in the last post by @mysql-oca-bot.

**Pull request closed without merging**
