### PR TITLE
fix: fix LocalizedErrorMessages.properties doc: less then -> less than

### PR DESCRIPTION
**Pull request by sdusongjian**

### CODE REVIEW

**Comment by sdusongjian** [comment]
收到～

**Comment by sdusongjian** [comment]
Hi, I signed the OCA, and submit this bug in bugs.mysql.com (Bug #106205). This is not a bug,just doc word not exact, only I think. Please check.

**Comment by sdusongjian** [comment]
收到～

**Comment by mysql-admin** [comment]
@sdusongjian Hi,
Please confirm the the code is under OCA by pasting the text in English as requested by the bot message above

Thanks for your contribution
==Omer

**Comment by sdusongjian** [comment]
I confirm the code being submitted is offered under the terms of the OCA, and that I am authorized to contribute it.

**Pull request closed without merging**
