### PR TITLE
Add maxResultBuffer property.

### PR DESCRIPTION
**Pull request by marszymb**
Add new property maxResultBuffer. Limits the number of bytes of the read result set.
It can be declare as: 
- size of bytes (100, 100K, 100M, 100G, 100T);
- percent of max heap memory (i.e. 10p, 10pct, 10percent).
Additionally there is validation if given value is not bigger than 90% of max memory heap.

If the new property is not declared, the driver works as before.

Commit made for Heimdalldata's request to solve memory problem during reading result set.

### CODE REVIEW

**Comment by marszymb** [comment]
Done.

**Comment by marszymb** [comment]
I confirm the code being submitted is offered under the terms of the OCA, and that I am authorized to contribute it.

**Comment by soklakov** [comment]
Hi Marcin,

Isn't it possible to just use a streaming or cursor-based result set as described on https://dev.mysql.com/doc/connector-j/8.0/en/connector-j-reference-implementation-notes.html ?

It's an application design responsibility to care about memory usage. It should be clear by design what amount of data is processed, and how to do that without critical affects for the memory.

If we limit memory usage on a driver side as you propose, it would only mean that user won't be able to retrieve the data, with no workaround.

**Comment by ebrandsberg** [comment]
> Hi Marcin,
> 
> Isn't it possible to just use a streaming or cursor-based result set as described on https://dev.mysql.com/doc/connector-j/8.0/en/connector-j-reference-implementation-notes.html ?
> 
> It's an application design responsibility to care about memory usage. It should be clear by design what amount of data is processed, and how to do that without critical affects for the memory.
> 
> If we limit memory usage on a driver side as you propose, it would only mean that user won't be able to retrieve the data, with no workaround.

This comment is assuming the developer has control over the query being made.  Consider situations like with DBeaver or worse, a system that is shared between many users that allows ad-hoc requests for say reporting.  In this case, the developer is simply passing a query through that a user has generated, and doesn't know prior how large the result will be.  This feature is designed to provide a last-ditch protection to prevent the system from overflowing in memory.  If the cursor-based results are used, than this feature will never be needed.  Likewise, it is not enabled by default.

**Comment by ebrandsberg** [comment]
> Hi, thank you for your contribution. Your code has been assigned to an internal queue. Please follow
> bug http://bugs.mysql.com/bug.php?id=100415 for updates.
> Thanks

There were two sets of code submitted, one for 5.1.x and one for 8.0.  it only appears that one patch was transitioned to the oracle bug tracker, the other was simply ignored--AND it was for the 5.1 branch, and rejected as being end of lifed.  So the patch for 8.x was never even considered.

**Pull request closed without merging**
