### PR TITLE
Update ReplicationConnectionGroup.java

### PR DESCRIPTION
**Pull request by cnhome**
When the Fabric changed localMasterList and localSlaveList, the masterHostList and slaveHostList should been changed.

### CODE REVIEW

**Comment by cnhome** [comment]
MySQL bug system user:lwz12@sina.com

**Comment by cnhome** [comment]
I have singed the OCA. Jackson Lee - MYSQL

**Comment by cnhome** [comment]
I confirm the code being submitted is offered under the terms of the OCA, and that I am authorized to contribute it.

**Comment by fjssilva** [comment]
This is not necessary. It's the sole purpose of FabricConnectionGroup.syncGroupServersToReplicationConnectionGroup() to synchronize and update the corresponding ReplicationConnectionGroup when it changes, even when establishing new Fabric connections.

Do you know of any situation where this could be needed? If so, please provide a test case.

Thanks,

**Pull request closed without merging**
