### PR TITLE
Release/8.0 【异常处理机制的疑问】Access denied for user 'xxxx_user'@'172.16.9.152' (using password: YES) to database 'xxxx_dbName'

### PR DESCRIPTION
**Pull request by gongzh021**
Exception in thread "main" java.sql.SQLException: Access denied for user 'xxxx_user'@'172.16.9.152' (using password: YES) to database 'xxxx_dbName'
at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:836)
at com.mysql.cj.jdbc.ConnectionImpl.(ConnectionImpl.java:456)
at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:246)
at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:197)
at java.sql.DriverManager.getConnection(DriverManager.java:664)
at java.sql.DriverManager.getConnection(DriverManager.java:270)
at com.xxxx.xxxx.util.JdbcUtil.main(JdbcUtil.java:17)

为什么连接密码错误之后，抛出这样的异常，172.16.9.152是本机IP，我看到这个错误的第一反应是 连接 172.16.9.152 这个地址出现了密码不正确，误导了我排错的方向

这样的提示错误，是否可以改一下，

### CODE REVIEW

**Comment by gongzh021** [comment]
> Hi, thank you for submitting this pull request. In order to consider your code we need you to sign the Oracle Contribution Agreement (OCA). Please review the details and follow the instructions at https://oca.opensource.oracle.com/ Please make sure to include your MySQL bug system user (email) in the returned form. Thanks

Do you understand my question?

**Comment by fjssilva** [comment]
Thank you for your interest in MySQL Connector/J.

Please submit all MySQL Connector/J questions to the [MySQL Forums](https://forums.mysql.com/list.php?39)

But, no. The error message can't be changed. It's a security measure. Replying that the password is wrong would disclosure too much information to a potential attacker.

**Comment by gongzh021** [comment]
> Thank you for your interest in MySQL Connector/J.
> 
> Please submit all MySQL Connector/J questions to the [MySQL Forums](https://forums.mysql.com/list.php?39)
> 
> But, no. The error message can't be changed. It's a security measure. Replying that the password is wrong would disclosure too much information to a potential attacker.


Thank you for your reply.
I know the security risks of printing passwords.
My confusion is the printing of IP.
I hope to get the attention of the community, cancel printing IP or print IP in other ways.

**Comment by fjssilva** [comment]
Discussion moved to [Connector/J, JDBC and Java](https://forums.mysql.com/read.php?39,704834,704834#msg-704834) forum.

**Pull request closed without merging**
