### PR TITLE
Remove unnecessary boxing in ResultSetImpl

### PR DESCRIPTION
**Pull request by ningpp**

### CODE REVIEW

**Comment by ningpp** [comment]
i signed the Oracle Contribution Agreement (OCA). what's next?

**Comment by mysql-admin** [comment]
@ningpp Sorry for the delay - we'll check the status of the OCA and follow up
Thanks for contributing to MySQL
==Omer

**Comment by mysql-admin** [comment]
@ningpp - sorry for the delay in processing your OCA. It  has been processed. Please confirm the code is under the OCA as requested by the bot

Thanks
==Omer

**Comment by ningpp** [comment]
I confirm the code being submitted is offered under the terms of the OCA, and that I am authorized to contribute it.

**Pull request closed without merging**
