### PR TITLE
Allow to disable AbandonedConnectionCleanupThread completely

### PR DESCRIPTION
**Pull request by turbanoff**
Allow to disable AbandonedConnectionCleanupThread completely via system property `com.mysql.disableAbandonedConnectionCleanup`

to disable it add following string to JVM command line: `-Dcom.mysql.disableAbandonedConnectionCleanup=true`

### CODE REVIEW

**Comment by turbanoff** [comment]
I've signed OCA

**Comment by turbanoff** [comment]
@mysql-oca-bot hello. As I said I've actually signed OCA.
Can you please reopen pull request?

**Comment by mysql-admin** [comment]
OCA in place but update missed by the script

**Comment by turbanoff** [comment]
I confirm the code being submitted is offered under the terms of the OCA, and that I am authorized to contribute it.

**Comment by quaff** [comment]
https://github.com/mysql/mysql-connector-j/pull/43 is related

**Comment by lefred** [comment]
Thank you for your contribution that has been added to 8.0.22: https://lefred.be/content/mysql-8-0-22-thank-you-for-the-contributions/

**Pull request closed without merging**
