### PR TITLE
add track session state change

### PR DESCRIPTION
**Pull request by WilliamLeeLoL**
1. add okpacket parse state change
2. add client track session switch
3. ResultSet add state change information

### CODE REVIEW

**Comment by WilliamLeeLoL** [comment]
I confirm the code being submitted is offered under the terms of the OCA, and that I am authorized to contribute it.

**Comment by xuanmiss** [comment]
@WilliamLeeLoL Hi, I encountered a problem, using mysql-connector 8.0.26 to connect to a database service using DBProxy, the error message on the server side is `java.lang.ArrayIndexOutOfBoundsException: 8`. The specific information is as follows. 

The Server version is `5.7.28-log` 


image
The `OkPacket` buffer starts with `0xFE` and the buffer length is `7`. At this time, when parsing the message, the error subscript is out of bounds.
image
image
**If you need some other information, please contact me, thank you very much, hope to hear from you**

**Comment by fjssilva** [comment]
Hi @xuanmiss, please upgrade to latest versions of MySQL and Connector/J. If the issue persists, please file a bug in https://bugs.mysql.com and provide a test case that reproduces the problem, as well as stack traces and other information you find relevant. Thanks,

**Comment by wylpfcz** [comment]
@xuanmiss Is the problem resolved after the upgrade?I had a similar problem 
bug

**Pull request closed without merging**
