### PR TITLE
Fix for Bug#84117 PreparedStatement support includeThreadNamesAsStatementComment

### PR DESCRIPTION
**Pull request by cxzl25**
https://bugs.mysql.com/bug.php?id=84117

### CODE REVIEW

**Comment by cxzl25** [comment]
@fjssilva  Please help to review, thanks.

**Comment by mysql-admin** [comment]
Hi @cxzl25,
We cannot review your contribution before you sign an OCA.
Please sign the OCA as listed above

Thanks for contributing to MySQL
==Omer

**Comment by cxzl25** [comment]
Now OCA has been approved.

@fjssilva Please help to review, thanks.

**Comment by cxzl25** [comment]
I confirm the code being submitted is offered under the terms of the OCA, and that I am authorized to contribute it.

**Pull request closed without merging**
